export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USER_TRACKS = "GET_USER_TRACKS";
export const SET_USER_TRACK = "SET_USER_TRACK";
export const MODIFY_NEW_TRACK = "MODIFY_NEW_TRACK";